version: '3.8'

services:
  client:
    image: syncmereg.azurecr.io/syncme-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

  server:
    image: syncmereg.azurecr.io/syncme-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
c