version: 2.1
orbs:
  go: circleci/go@1.7.1
jobs:
  build-and-run-test:
    executor:
      name: go/default
      tag: "1.21"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Run tests
          command: go test -v
  build-docker-image:
    docker:
      - image: cimg/go:1.18.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      -run:
        name: Build and push Docker image
        command: |
          docker build -t syncmereg.azurecr.io/syncme-server:latest .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin syncmereg.azurecr.io
          docker push syncmereg.azurecr.io/syncme-server:latest
workflows:
  test-and-deploy:
    jobs:
      - build-and-run-test
      - build-docker-image:
          requires:
            - build-and-run-test